config/routes.rb
Rails.application.routes.draw do

  get 'session/new'

  root "pages#index"
    get 'pages/index'

  resources :reservations
  resources :flights
  resources :planes
  resources :users

  get '/login' => 'session#new', :as => "login"
  post '/login' =>'session#create'
  delete '/logout' => 'session#destroy', :as => "logout"

end

app/models/flight.rb
class Flight < ActiveRecord::Base

  # has_many :reservations
  belongs_to :plane
  has_many :users, through: :reservations
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flightref, :date, :to, :from, :plane_id)
    end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flightref %><br>
    <%= f.text_area :flightref %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :to %><br>
    <%= f.text_area :to %>
  </div>
  <div class="field">
    <%= f.label :from %><br>
    <%= f.text_area :from %>
  </div>
  <div class="field">
    <%= f.label :plane_id %><br>
    <%= f.text_area :plane_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<div id="app">
  <h1>Flights</h1>
</div>

<!-- Below is the template for our app.AppView -->
<script type="underscore/template" id="appViewTemplate">
  <h1>Our Flights App</h1>

  <div id="flightForm">This should show flights</div>
  <table id="flights">
    <tr>
      <th>Date</th>
      <th>FlightRef</th>
      <th>From</th>
      <th>To</th>
      <th>Plane</th>
    </tr>

  </table>
</script>



<!-- Below is the template for our app.FlightSearchView -->

<script type="underscore/template" id="flightSearchViewTemplate">
  <textarea placeholder="Search for your flight"></textarea>
  <button>Submit</button>
</script>

<p></p>
<br>
<br>

<div class="reservations"><h2>Reservations</h2>

</div>
<div class="app2">
</div>


<script type="underscore/template" id="reservationViewTemplate">
  <h1>Seating plan</h1>
  <div id="seatPlanViewForm">This should show seat</div>


</script>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flightref:</strong>
  <%= @flight.flightref %>
</p>

<p>
  <strong>Date:</strong>
  <%= @flight.date %>
</p>

<p>
  <strong>To:</strong>
  <%= @flight.to %>
</p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>Plane:</strong>
  <%= @flight.plane %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>